language: cpp

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/miniconda

before_install: # Use instead CC and CXX from miniconda (https://docs.travis-ci.com/user/languages/cpp/#mpi-projects)
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - bash ci/travis/install.sh

script:
  - bash ci/travis/test.sh

before_cache:
  - rm -f $HOME/miniconda/envs/autodiff/conda-meta/history*  # Delete these history files to prevent a new cache upload step.
