name: autodiff

dependencies:
  - cmake>=3.13
  - ninja
  - eigen
  - catch2
  - gxx_linux-64=7.3.0  # [linux]
  - clangxx_osx-64=9.0.0  # [osx]
  - ccache  # [unix]
  - pip
  - pip:
    - mkdocs
    - mkdocs-material
    - mkdocs-macros-plugin
