name: windows

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1

    - name: Conda
      shell: cmd
      run: call ci\actions\configure-conda-windows.bat

    - name: Install
      shell: cmd
      run: |
        set CONFIGURATION=${{ env.configuration }}
        call ci\actions\install-autodiff-windows.bat

    - name: Test
      shell: cmd
      run: |
        set CONFIGURATION=${{ env.configuration }}
        call ci\actions\test-autodiff-windows.bat
